### ISSUE TITLE
URL redirect update

### ISSUE THREAD

**Issue by hulank** [kivuto/lp-studentadvantage#4]
Hey Jesse,

For the LP, we'd like the URL to be always kivuto,com/office365 .

Right now we redirect  kivuto,com/office365   to   http://kivuto.com/microsoft-student-advantage-deployment/ 

Can we have it so that  http://kivuto.com/microsoft-student-advantage-deployment/   redirects to   kivuto,com/office365

**Comment by jburcsik** [comment]
Closing because #6
