### ISSUE TITLE
Add comparison document to the SA landing page

### ISSUE THREAD

**Issue by hulank** [kivuto/lp-studentadvantage#5]
Hi Dylan,

Attached is the document to be hosted on the kivuto.com/office365 page. This will fill in the 'coming soon' space. 

[ELMS for O365 - Fully Managed Solution - Service Comparison.pdf | uploaded via ZenHub](https://files.zenhub.io/54625191c3cc8d7f4c384113)

**Comment by hulank** [comment]
Hey @jburcsik @dylanhochreiter 
Can we set this up for Monday? MS will be doing email blasts to their clients on this initiative and we should have the comparison up.  It's just to host a doc on LP

**Comment by jburcsik** [comment]
Hey Katie,

Sorry for not getting back to you on this. I'll make sure to look at new issues more closely coming in on git. I'll out this in the queue for today.

**Comment by jburcsik** [comment]
http://staging.kivuto.com/microsoft-student-advantage-deployment/

Tested. Pushing Live.

**Comment by jburcsik** [comment]
Live

**Comment by hulank** [comment]
hey Jesse,

I see it on staging. I keep refreshing on live but it's not appearing. Can you double check prod?

**Comment by jburcsik** [comment]
Positive it’s there. Double checked. From two separate server locations.

 
 
************************************************************************************
This footnote confirms that this email message has been scanned by
PineApp Mail-SeCure for the presence of malicious code, vandals & computer viruses.
************************************************************************************
