### ISSUE TITLE
Office365 URL isn't sticking

### ISSUE THREAD

**Issue by hulank** [kivuto/lp-studentadvantage#7]
The kivuto.com/office365 url isn't staying... it redirects to the older URL of http://kivuto.com/microsoft-student-advantage-deployment/

**Comment by jburcsik** [comment]
Does this mean you want the URL to actually be Office365 and to have the current URL redirect to Office365?

**Comment by hulank** [comment]
Yes sir!!

**Comment by jburcsik** [comment]
Closing because #6
