### ISSUE TITLE
Remove promo date on April 21 AM

### ISSUE THREAD

**Issue by gustavojsm** [kivuto/lp-studentadvantage#9]
@hulank and @jburcsik , the free SA promo ends on April 20. We need to either update the LP at midnight or soon after to remove the mention of the free service.

@jburcsik Can we see the old content that was there before the promo?

@hulank forgot to add this to the priorities, its for next week but im sure we'll have to work on it this week

**Comment by hulank** [comment]
The last two blocks should look like what I've attached
![previous o365 page](https://cloud.githubusercontent.com/assets/7725620/7142149/5a65a5dc-e2a4-11e4-9d86-3dddbaf25da5.PNG)

**Comment by hulank** [comment]
The content on first block should read:

Larger text: Easily manage 
Office 365 ProPlus 

Smaller text:  Fast setup. Automated management. Reliable customer care.

**Comment by hulank** [comment]
@jburcsik, can you see what we have hosted for pricing sheet currently?

I need to update the Overview document to remove the info on the promo

**Comment by jburcsik** [comment]
To confirm I will update the content on the first block.

Is this the document you are looking for: 
https://github.com/kivuto/lp-studentadvantage/blob/master/docs/Kivuto%20-%20ELMS%20for%20Office%20365%20Overview.pdf

@hulank Can you send me the updated $ image or have @cbridges do so please.

**Comment by hulank** [comment]
That’s a different doc. I noticed we have old KVT logos on all. We’ll need to update all hosted docs now.

Will send new ones to be hosted soon.

Chrissy can send image

**Comment by hulank** [comment]
Hi Jesse,

We have 4 new documents that need to be hosted on Monday night when the change happens on LP. I wasn't able to upload docs here so I made an Asana task here with all docs:

**Comment by jburcsik** [comment]
Oh that's weird, do you have the ZenHub chrome plugin installed? 

See the box in the top right of the box... It allows ALL file types to be uploaded for the future.

![image](https://cloud.githubusercontent.com/assets/1092839/7159512/a80cb60c-e350-11e4-91f4-9c9b7f838463.png)

**Comment by hulank** [comment]
Yeah, I find it is buggy. I uploaded 3 times and it didn’t stay- error. When I returned after asana it was there – but still with error. Guess it’s patience and ignoring error messages. :s
